import type { Card } from '../types'

export const CHINESE_SAYINGS_DECK: Card[] = [
  {
    phrase: '叶公好龙 (yè gōng hào lóng)\nLord Ye Who Loved Dragons',
    answer: "Lord Ye loved dragons so much that he covered his entire mansion in dragon paintings, carvings, and sculptures. Upon hearing of his devotion, a real dragon descended from heaven to visit. Lord Ye ran away screaming. The idiom — 2,500 years old — means claiming to love or support something while being completely unable to endure it when it makes actual demands. Today it describes people who claim to love spicy food until the real thing arrives, companies that publicly champion innovation until it threatens their existing product, and politicians who champion reform until asked to implement it. The dragon always shows up eventually.",
  },
  {
    phrase: '问鼎中原 (wèn dǐng zhōng yuán)\nAsking the Weight of the Cauldron',
    answer: "The nine ceremonial bronze cauldrons of the Zhou dynasty were the physical embodiment of the mandate to rule China. When the King of Chu sent an envoy to ask about the 'weight and size' of the cauldrons, the Zhou minister understood immediately: this was a declaration of intent to overthrow the dynasty. Asking the weight of the cauldrons became the permanent idiom for harboring imperial ambitions. Today it appears in sports commentary when a team announces championship intentions, in business reporting about a company making a play for market dominance, and in political analysis whenever a regional power signals broader aspirations. The cauldrons disappeared. The phrase did not.",
  },
  {
    phrase: '金屋藏娇 (jīn wū cáng jiāo)\nA Golden House to Keep Her In',
    answer: "Emperor Wu of Han, as a child of five, was asked which girl he would like to marry. He allegedly replied: 'If I could have A'jiao, I would build her a golden house to live in.' A'jiao was his own cousin. He did marry her and build her extravagant palaces. When she failed to produce an heir, he replaced her with a servant girl. The idiom now means keeping a mistress in lavish private accommodation. Today it appears in tabloid real estate reporting — a second apartment purchased in a different city is immediately labeled 金屋藏娇 by gossip media. It is also shorthand for any secret arrangement maintained at considerable expense, particularly when the hidden party is eventually made public.",
  },
  {
    phrase: '悬梁刺股 (xuán liáng cì gǔ)\nRope to the Beam, Awl to the Thigh',
    answer: "Sun Jing tied his hair to a roof beam so that if he fell asleep studying, the pain would wake him. Su Qin stabbed his own thigh with an awl during marathon study sessions to stay conscious. Both passed their examinations and became famous officials. The idiom is standard motivational content in Chinese schools from the Tang dynasty to the present. Today it is invoked during gaokao season in every parent's speech and teacher's pep talk. It is also used sardonically in tech and startup culture to describe self-imposed extreme work schedules. Students are expected to find it encouraging. The awl remains on the motivational poster regardless.",
  },
  {
    phrase: '囊萤映雪 (náng yíng yìng xuě)\nFireflies in a Bag, Reading by Snow',
    answer: "Che Yin was too poor to buy lamp oil, so he caught fireflies and put them in a cloth bag to read by at night. Sun Kang had no fireflies, so he read by moonlight reflected off snow. Both eventually passed the imperial examinations. Today the idiom is standard motivational content in children's education — used by parents describing their own hardships and teachers invoking historical precedent. It is also used with light sarcasm: 'I'm not asking you to 囊萤映雪 — just put down your phone.' Its practical advice about alternative lighting sources has never been seriously tested by anyone who has actually tried to read by firefly.",
  },
  {
    phrase: '摊书卧读 (tān shū wò dú)\nSpreading Books, Reading Lying Down',
    answer: "Wang Xizhi, the greatest calligrapher in Chinese history (4th century), reportedly preferred to read lying flat on his stomach, spreading books across the floor and moving from page to page without getting up. This posture became associated with a particular intellectual nonchalance that later Neo-Confucian society considered mildly scandalous, as it violated proper bodily decorum during study. Since Wang Xizhi was too historically important to criticize, biographers simply noted the habit with visible admiration. Today the idiom is occasionally deployed as historical justification for reading in bed or in unconventional postures. 'Wang Xizhi did it' is the defense.",
  },
  {
    phrase: '嗜痂之癖 (shì jiā zhī pǐ)\nThe Habit of Eating Scabs',
    answer: "This idiom originates from a historical record about a Jin dynasty official named Liu Piao who genuinely ate scabs from wounds and reportedly enjoyed them. Rather than being condemned, the story was preserved as a curiosity in the dynastic histories. The idiom now means any deeply peculiar personal taste that others find incomprehensible. Today it is used for acquired tastes in food, music, and entertainment that others cannot understand. '这只是嗜痂之癖而已' (it's just a 嗜痂之癖) is the sophisticated way to say: leave me alone about what I enjoy. The scabs are not the point. The tolerance for inexplicable preference is.",
  },
  {
    phrase: '狗尾续貂 (gǒu wěi xù diāo)\nDog Tail Completing Sable',
    answer: "During the Jin dynasty, the Emperor awarded the rank of marquis so recklessly that there were not enough sable furs to trim all the ceremonial hats. Court tailors were forced to complete the hats using dog tails. A satirical poem of the period gave us this idiom. Today it is one of the most common phrases in Chinese entertainment criticism — deployed without hesitation about disappointing sequels, weak follow-up albums, forgettable second seasons of successful shows, and any novel written after the original author's death. Chinese film reviews use it with particular frequency during franchise season. The dog tail is understood.",
  },
  {
    phrase: '莼羹鲈脍 (chún gēng lú kuài)\nWater Shield Soup and Sea Bass',
    answer: "A Jin dynasty official named Zhang Han, posted far from home, suddenly smelled autumn in the air and was overcome by an unbearable craving for the water shield soup and sea bass slices of his hometown. He immediately resigned his government position and returned home to eat them. Today the idiom is used by overseas Chinese in exactly this spirit — a specific dish from home that makes a stable foreign career feel suddenly optional. It also appears in lifestyle writing about career vs. comfort decisions, and in food columns about hometown specialties. It is the most literarily prestigious way in Chinese to describe quitting your job to go eat something.",
  },
  {
    phrase: '白马非马 (bái mǎ fēi mǎ)\nA White Horse Is Not a Horse',
    answer: "The philosopher Gongsun Long (4th century BCE) argued with complete logical seriousness that a white horse is not a horse: 'horse' refers to form; 'white' refers to color; a compound term specifying both refers to neither alone — therefore 'white horse' refers to something categorically distinct from 'horse.' He debated this at city gates and reportedly won every argument. It drove everyone else insane. Today the idiom is used for technical arguments that are logically valid but obviously wrong in practical spirit — legal loopholes, regulatory workarounds, contract technicalities. '这是白马非马的逻辑' (this is 白马非马 logic) means: you are technically correct and completely missing the point.",
  },
  {
    phrase: '目无全牛 (mù wú quán niú)\nEyes That See No Whole Ox',
    answer: "From Zhuangzi's story of Cook Ding, who had become so skilled at butchering oxen that he no longer saw the whole animal at all — only the spaces between tendons, the gaps between bones, the natural pathways along which his blade moved without encountering resistance. He had never sharpened his cleaver in nineteen years. The idiom means supreme mastery through complete internalization of a skill. Today it is used to describe expert professionals operating in a state of flow: a surgeon who no longer consciously thinks about the procedure, a programmer who writes code without deliberating over syntax. The opposite meaning — arrogant blindness to the whole — is also in circulation, which has caused considerable confusion.",
  },
  {
    phrase: '悬鱼太守 (xuán yú tài shǒu)\nThe Governor Who Hung Fish',
    answer: "Yang Zhen (Eastern Han dynasty) was repeatedly offered bribes by officials hoping to curry favor. When one briber sent a gift of fish, Yang Zhen accepted it — then hung it outside his office gate and left it there until it rotted publicly in full view of the entire city. He refused nothing quietly. The rotting fish became his public statement of incorruptibility. Today the idiom describes officials or executives who make a conspicuous public show of refusing improper gifts — using the refusal itself as a moral performance. It is used admiringly when the gesture is genuine and sardonically when it appears calculated. In Chinese anti-corruption discourse, 悬鱼 appears as a historical model for transparent integrity.",
  },
  {
    phrase: '染指于鼎 (rǎn zhǐ yú dǐng)\nDip a Finger in the Royal Cauldron',
    answer: "From Zuo Zhuan. The minister Zi Gong of Zheng heard that a giant turtle was being cooked as a ceremonial offering for the duke. He walked into the kitchen, dipped his finger into the royal cauldron, tasted the broth, and walked out. The cauldron was ritually untouchable. When confronted by the furious duke, Zi Gong had nothing to say that served him. The duke had him killed. Today the idiom describes taking an unauthorized share of something — specifically the first uninvited taste that establishes a claim. It is used in business contexts about people who insert themselves into deals they were not party to, and in financial discussions about unauthorized profit-taking. Whether the turtle was worth it is not recorded.",
  },
  {
    phrase: '讳莫如深 (huì mò rú shēn)\nHidden Deeper Than Anything',
    answer: "From Zuo Zhuan. When the ruler of Ju died, the manner of his death was considered so dangerous to record that the court erased it from the official annals entirely — not replaced with a euphemism, simply blank. The historian Gu Liang noted: when something is concealed more completely than anything else, there is something worth concealing. Today the idiom is a staple of corporate PR coverage and political scandal reporting. '对这件事讳莫如深' (being 讳莫如深 about something) means: their total silence is itself the most informative thing they have said. It is used whenever official non-responses are more revealing than any statement could be.",
  },
  {
    phrase: '韦编三绝 (wéi biān sān jué)\nThe Leather Binding Broke Three Times',
    answer: "Before paper, Chinese books were strips of bamboo connected by leather cords. Confucius studied the Book of Changes with such sustained intensity that the leather binding of his personal copy snapped completely three separate times and had to be replaced. He also said he wished he had fifty more years for this one text alone. Now means exceptional devotion to sustained study. Today it is used to describe people who have read a book so many times the spine fell apart, scholars who have worn out multiple copies of a primary text, and anyone whose relationship with a particular work has left physical evidence. Books do not generally break from being read. His did.",
  },
  {
    phrase: '投鞭断流 (tóu biān duàn liú)\nThrow Riding Crops to Dam the River',
    answer: "In 383 CE, the ruler Fu Jian assembled an army of 870,000 soldiers to destroy the Eastern Jin dynasty. When advisers urged caution, he replied that if every soldier threw their riding crop into the Yangtze, the volume of wood would dam the current. His 870,000 were routed at the Battle of Fei River by approximately 80,000 Jin troops — one of the largest military reversals in Chinese history. Today the idiom is used in post-defeat analysis: 'they went in with a 投鞭断流 mentality' means catastrophic overconfidence. It also appears as a warning label for any plan that depends on numerical overwhelming rather than strategic thinking. The Yangtze continued flowing.",
  },
  {
    phrase: '梦笔生花 (mèng bǐ shēng huā)\nDream of a Brush Blooming with Flowers',
    answer: "A Tang dynasty account states that Li Bai dreamed his brush bloomed with flowers at its tip. When he woke, his poetry had changed. The story circulated to explain the transition from his earlier work to his mature style. Now means exceptional literary talent arriving or emerging suddenly. Today the idiom is used to describe a creative breakthrough moment — when a writer suddenly finds their voice, a musician discovers a new direction, or an artist's style crystallizes. 'That album was his 梦笔生花 moment' means: something shifted and the work was never the same again. Li Bai left no record of the dream. The record was made by someone watching from outside.",
  },
  {
    phrase: '枕戈待旦 (zhěn gē dài dàn)\nSleeping on a Spear, Waiting for Dawn',
    answer: "Liu Kun served the Western Jin dynasty as it collapsed, defending northern territory while the court retreated south. He slept with his spear as a pillow — not metaphorically, but as a physical practice, to prevent the ease of sleep from dulling the urgency of his situation. A colleague sent him geese as a gift; Liu Kun wrote back that their honking before dawn reminded him each morning of his duty to march north. He died before he could march. Today the idiom is used in business: entrepreneurs who sleep with their phones on, teams waiting anxiously for regulatory approval, anyone who cannot fully rest because conditions require constant alertness. The spear under the head is the discomfort that keeps you sharp.",
  },
  {
    phrase: '程门立雪 (Chéng mén lì xuě)\nStanding in Snow at Master Cheng\'s Door',
    answer: "The Song dynasty scholar Yang Shi traveled specifically to study under the Neo-Confucian philosopher Cheng Yi. He arrived to find Cheng Yi in seated meditation. Yang Shi refused to leave or enter — to leave would break the silence; to enter would violate the teacher's concentration. He stood at the entrance and waited. Cheng Yi opened his eyes to find snow piled to Yang Shi's knees. Today the idiom is used to describe patient, respectful waiting in applications to mentors, requests for senior guidance, or any situation requiring sustained patience to access someone of significantly higher standing. The detail consistently omitted: Yang Shi was forty years old and already an established official when he stood in that snow.",
  },
  {
    phrase: '请君入瓮 (qǐng jūn rù wèng)\nPlease, Sir, Enter the Vat',
    answer: "The Tang official Zhou Xing had built a reputation for extracting confessions by sealing prisoners inside a heated vat. When he himself was accused of treason, his colleague Lai Junchen invited him to dinner. Over wine, Lai asked: 'If a prisoner refuses to confess, what method do you recommend?' Zhou Xing enthusiastically described the heated vat. Lai had one brought in, lit the fire underneath, and said: 'There is an imperial order to investigate you. Please, sir, enter the vat.' Zhou Xing confessed immediately. Today the idiom is used when an investigation uses a suspect's own methods against them, when a platform's own rules are invoked to remove the platform's creators, or in any negotiation where someone's prior position becomes the trap they fall into.",
  },
  {
    phrase: '尸位素餐 (shī wèi sù cān)\nCorpse Occupying the Position, Eating Plain Rice',
    answer: "The 尸 here is not a dead body — it refers to the ritual stand-in in ancient Chinese ceremony. When a deceased ancestor was being honored, a living person was appointed to physically occupy their place and receive the food offerings, performing no active function. To hold a 尸位 is to occupy a title and draw a salary while contributing nothing. Today this is one of the most commonly used workplace idioms in Chinese organizational culture — deployed in performance reviews, management critiques, and resignation letters. '某些领导只是在尸位素餐' (some leaders are just 尸位素餐-ing) is a standard formulation in workplace complaint culture. The ritual was abolished two thousand years ago. The behavior it describes has not been.",
  },
  {
    phrase: '望洋兴叹 (wàng yáng xīng tàn)\nGazing at the Ocean and Sighing',
    answer: "From Zhuangzi. The god of the Yellow River, swollen with autumn floods, assumes he is the greatest body of water that exists. He flows east until he reaches the North Sea and cannot see the other shore. He sighs to the Sea God and admits his smallness. 望洋 does not literally mean looking at the sea — 洋 here is an archaic term for the vast and boundless. The sigh is specifically the sigh of someone who has just encountered something so much larger than themselves that their previous certainty of scale collapses. Today it is used when facing a task of overwhelming scope or a competitor of overwhelming capability. '读完他的论文，只能望洋兴叹' is the scholar's most elegant way of saying: I am humbled.",
  },
  {
    phrase: '囫囵吞枣 (hú lún tūn zǎo)\nSwallowing Dates Whole',
    answer: "A doctor explained that pears benefit the teeth but harm the spleen, while dates benefit the spleen but harm the teeth. A listener announced he had found the solution: he would chew the pears before spitting them out, and swallow the dates whole without chewing. Neither organ would be harmed. The doctor said nothing. Today the idiom is used constantly in education and knowledge-work contexts: '别囫囵吞枣' (don't swallow dates whole) is a standard warning against surface-level learning or fast reading without retention. It is said by teachers to students before exams, by managers to new employees about company policies, and by anyone who suspects the other person has technically consumed the content without actually digesting any of it.",
  },
  {
    phrase: '邯郸学步 (hándān xué bù)\nLearning to Walk in Handan',
    answer: "From Zhuangzi. Handan was famous for the elegance of its people's gait. A young man from the State of Yan traveled there to learn how Handan residents walked. Before he mastered the Handan style, he forgot how he himself used to walk. He crawled home on his hands and knees. Today the idiom is used in discussions about cultural appropriation, awkward brand localization, and personal identity lost to imitation. It appears in business analysis about companies that copy competitors without understanding the underlying logic, losing their own identity in the process. '别邯郸学步了' means: don't abandon what makes you yourself in pursuit of something that wasn't yours to begin with.",
  },
  {
    phrase: '马革裹尸 (mǎ gé guǒ shī)\nWrapped in Horse Hide',
    answer: "Said by the Eastern Han general Ma Yuan when a friend urged him to take fewer risks. 'A man should die on the battlefield with his body wrapped in horse hide — not in bed, attended by women and children.' He said this at age 60 and immediately departed for a campaign in southern China. He died there. His body was returned wrapped in a mat because horse hide was unavailable. Today the idiom is used in military memorial contexts and in startup culture to describe total commitment — 'I'll 马革裹尸 before I give up on this company.' It is also used about people who want to work until they die rather than retire. The horse hide part did not even happen.",
  },
  {
    phrase: '得陇望蜀 (dé lǒng wàng Shǔ)\nHaving Gained Gansu, Coveting Sichuan',
    answer: "Emperor Guangwu of the Eastern Han had just completed a successful campaign in the Longxi region. His general Cen Peng wrote to ask permission to immediately move on the Shu region. The emperor's reply contains the idiom: 'Human desire has no limit — having just taken Longxi, you are already coveting Shu.' Today it is used in business strategy discussions about overexpansion, in geopolitical analysis about territorial ambition, and in personal finance commentary about people who achieve one target and immediately raise expectations without enjoying the achievement. '别得陇望蜀了' is the gentle reminder that satisfaction is possible. The emperor who coined it had spent years acquiring the empire that allowed him to counsel restraint.",
  },
  {
    phrase: '噤若寒蝉 (jìn ruò hán chán)\nSilent as a Cicada in the Cold',
    answer: "The official Liu Bao watched his colleague Zhang Jian unjustly punished for speaking out — stripped of position, publicly humiliated. Afterward, Liu Bao became completely silent on all court matters. A historian described him as 噤若寒蝉 — silent as a cicada in autumn, when the cold has shut down its song. Cicadas in summer are impossibly loud; in late autumn they go completely silent before dying. Today it describes workplace silence after a visible firing, online self-censorship after a controversial post, or any social environment where a public punishment has produced total behavioral compliance. '整个部门都噤若寒蝉了' means: one person was made an example and nobody has said anything since.",
  },
  {
    phrase: '管中窥豹 (guǎn zhōng kuī bào)\nViewing a Leopard Through a Tube',
    answer: "Wang Xizhi's young son Wang Xianzhi was watching adults play a board game and announced that a player had made a poor move. The adults told him to go away. He replied: viewing a leopard through a tube, he had only seen one spot — but one spot was enough to identify the animal. In its original usage the phrase was a defense: from a small sample you can know the whole. The phrase has since reversed: it now primarily means seeing only a small part of something and mistaking it for the whole. Today it is used in data analysis, media criticism, and research: 'Drawing conclusions from one data point is pure 管中窥豹.' The child who said it became one of the greatest calligraphers in history.",
  },
  {
    phrase: '覆水难收 (fù shuǐ nán shōu)\nSpilled Water Cannot Be Gathered Back',
    answer: "Jiang Ziya spent decades studying and doing nothing useful while his wife managed their poverty. When she finally left him, he poured a bucket of water on the ground and told her: if she could gather the water back up, he would take her back. She could not. Later, when Jiang Ziya became chief strategist of the Zhou dynasty, his wife returned. He poured water on the ground again. She tried to gather the mud. He said the water was gone. Today the idiom is used in relationship advice after major arguments, in business contexts about irreversible decisions, and in legal commentary about actions that cannot be undone. '覆水难收' is the dignified way to say: this cannot be fixed. It is also used pre-emptively as a warning about the permanence of certain choices.",
  },
  {
    phrase: '炉火纯青 (lú huǒ chún qīng)\nFurnace Fire Turning Pure Blue',
    answer: "In Daoist alchemy, the refinement of elixirs required sustained fire applied over months. The fire passes through stages: first red, then orange, finally — at the highest achievable temperature — pure blue. Pure blue fire meant the elixir was complete and the process had reached its limit. Today the idiom is used to describe expertise at the highest level: a chef whose technique is 炉火纯青 has nothing left to learn in that domain. It is common in food writing, martial arts commentary, and craftsperson profiles. '他的厨艺已经炉火纯青' (his culinary skill is now 炉火纯青) is high praise in Chinese food culture. The fire color was the original quality indicator. The metaphor transferred to every human skill in which there is a recognizable ceiling.",
  },
  {
    phrase: '沐猴而冠 (mù hóu ér guàn)\nMonkey Wearing a Crown',
    answer: "As the Qin dynasty collapsed, Xiang Yu captured the capital Xianyang and was urged to establish power there. He refused and moved east to his home territory. An adviser commented bitterly: 'People say a monkey wearing a hat is still a monkey. Now I believe it.' The comment reached Xiang Yu, who had the adviser boiled alive. Today the idiom is used to criticize people who have achieved status without the substance to match it — new money who cannot manage wealth, quickly promoted executives who cannot manage people, influencers whose credentials do not match their confidence. '这不就是沐猴而冠嘛' is the cutting dismissal. Xiang Yu boiled the man for saying it, then became the historical proof of the idiom's accuracy.",
  },
  {
    phrase: '图穷匕见 (tú qióng bǐ xiàn)\nMap Unrolled to the End, Dagger Appears',
    answer: "The assassin Jing Ke was admitted to the King of Qin's court carrying a poisoned dagger inside a rolled diplomatic map. As he unrolled the map slowly, the king leaned in. At the final unrolling, the dagger appeared. Jing Ke grabbed the king's sleeve and lunged. The king pulled away — the sleeve tore — and ran around a pillar while his ministers stood frozen, weapons forbidden in the throne room. The assassination failed. Now means the moment a concealed intention is finally revealed. Today it is used in negotiation breakdowns, political confrontations, and corporate strategy reveals: 'At the final board meeting, 图穷匕见' means that after months of careful positioning, the real agenda became visible. The map is always the performance.",
  },
  {
    phrase: '临渴掘井 (lín kě jué jǐng)\nDigging a Well Only When Thirsty',
    answer: "The image is precise: not failing to dig a well, but beginning to dig only at the moment of desperate thirst. It takes time to dig a well. A person who begins digging only when already thirsty will die of thirst before the well reaches water. From the Guanzi, approximately 300 BCE, used to argue that governance requires preparation before crisis, not improvisation during it. Today it is used in disaster preparedness, healthcare, financial planning, and academic contexts. '别等到临渴掘井' (don't wait until you're 临渴掘井) is the standard warning about procrastinated preparation — said before gaokao season, before job markets tighten, before any deadline that was visible long in advance.",
  },
  {
    phrase: '哀鸿遍野 (āi hóng biàn yě)\nMournful Geese Across the Fields',
    answer: "From the Book of Songs, a poem about displaced people during upheaval. The mournful cry of wild geese flying without a fixed landing place became the classical image of refugees — people separated from home, moving without destination, calling out without answer. Now means widespread suffering visible across a large population. Today it is used in economic downturn reporting, layoff season coverage, and mass event commentary. '行业哀鸿遍野' (the industry is 哀鸿遍野) means sector-wide suffering — not isolated incidents but a landscape of casualties. It is the literary register for what news would call 'widespread impacts.' The geese are still moving in the phrase, more than twelve hundred years after the poem.",
  },
  {
    phrase: '朝秦暮楚 (zhāo Qín mù Chǔ)\nMorning in Qin, Evening in Chu',
    answer: "During the Warring States period, the small states on the border between Qin and Chu changed allegiance so frequently — depending on which army was currently closer — that the expression entered the language. Morning under Qin, evening under Chu, sometimes multiple times in a week. Today the idiom is used about career hoppers, political opportunists, companies that switch strategy with every market trend, and romantic faithlessness. '他这个人朝秦暮楚的' (this person is 朝秦暮楚) means: do not count on their loyalty. The original borderland communities were doing the only thing that kept them alive. Whether modern applications are as forgivable is left as an exercise.",
  },
  {
    phrase: '风马牛不相及 (fēng mǎ niú bù xiāng jí)\nHorses and Cattle in Rut That Cannot Reach Each Other',
    answer: "From Zuo Zhuan, 656 BCE. The State of Qi invaded the State of Chu, and Chu sent an envoy to ask why. The Qi minister cited Chu's failure to send tribute to the Zhou king. The Chu envoy's response: 'Our two states are so far apart that even our horses and cattle in season would not be able to reach each other's herds — meaning we have no basis for any relationship, let alone a quarrel.' Today '风马牛不相及' is the standard phrase for completely irrelevant comparison or argument — 'these two issues are 风马牛不相及' means they have no connection whatsoever. The animals have been doing diplomatic work in this phrase for 2,600 years.",
  },
  {
    phrase: '相濡以沫 (xiāng rú yǐ mò)\nMoistening Each Other with Foam',
    answer: "From Zhuangzi. Two fish are stranded together in a drying wheel rut. Without water, they keep each other alive by breathing foam onto each other's gills. Zhuangzi follows this immediately with: 'Better if they had never met and could each swim freely in the rivers and lakes.' The mutual dependency that keeps them alive is also evidence of their shared catastrophe. Today '相濡以沫' is a standard caption for elderly couple photographs and long-term partnership celebrations — the modern usage considers it the definition of devoted love. Zhuangzi considered the situation a tragedy. These two readings have coexisted without resolving for two thousand years.",
  },
  {
    phrase: '手不释卷 (shǒu bù shì juàn)\nHand Never Releasing the Book',
    answer: "Sun Quan, ruler of Eastern Wu during the Three Kingdoms period, urged his general Lü Meng to study. Lü Meng protested that military service left no time for books. Sun Quan replied: 'I am not asking you to become a scholar. Just read histories and military texts. I am busier than any general and I have never let go of my books.' Lü Meng studied and transformed, becoming one of the most effective strategists of the period. Today '手不释卷' is used to describe devoted readers and serious students. It is also used sardonically about phone addiction: 'everyone is 手不释卷 now — just not with books.' The general who protested he had no time became the example the reading habit used to prove its own value.",
  },
  {
    phrase: '南橘北枳 (nán jú běi zhǐ)\nSouthern Orange Becomes Northern Trifoliate',
    answer: "Yan Zi, the brilliant Qi diplomat, was sent to Chu as an envoy. The King of Chu had a Qi criminal paraded before him and announced mockingly: 'People from Qi are apparently thieves.' Yan Zi replied: 'The orange tree transplanted south of the Huai River grows sweet oranges. The same tree transplanted north grows trifoliate thorns — bitter and useless. The soil changes the tree. Your kingdom's soil produced the criminal, not ours.' The king was silenced. Today it is used in education debates about resource inequality, in corporate culture discussions about talent thriving in some organizations and failing in others, and in arguments about whether personal failure is individual or systemic. '这是南橘北枳的问题' means: the person didn't fail — the environment failed the person.",
  },
  {
    phrase: '郑人买履 (zhèng rén mǎi lǚ)\nThe Man from Zheng Who Bought Shoes by Measurement',
    answer: "A man from the State of Zheng wanted to buy sandals. He carefully measured his foot and wrote it down. He traveled to the market, arrived, and reached for the slip — and found he had left it at home. He went home to get it, came back, and the stall had closed. A bystander said: 'Why didn't you just try them on?' He replied: 'I trust the measurement more than I trust my own foot.' Today it is used for bureaucratic formalism, regulatory literalism, and corporate compliance culture. '这就是郑人买履' means: the regulation says X but the actual situation is Y and someone chose the regulation. The foot was right there. The measurement was preferred. The stall closed.",
  },
  {
    phrase: '按图索骥 (àn tú suǒ jì)\nSeeking a Horse by Its Picture',
    answer: "The legendary horse expert Bo Le wrote a book on identifying exceptional horses with detailed descriptions and illustrations. His son took the book and went out to find such horses himself. He spotted a toad and brought it home excitedly, telling his father he had found a horse matching the description almost exactly — prominent eyes, broad forehead — though the hooves were somewhat unusual. Bo Le reportedly wept with laughter. Today it is used about hiring managers who only interview candidates matching job descriptions exactly, investors who follow checklists without reading the company, and any process that confuses the map for the territory. '按图索骥地找人才' (finding talent by 按图索骥) means: hired the resume, not the person.",
  },
  {
    phrase: '买椟还珠 (mǎi dú huán zhū)\nBuying the Box and Returning the Pearl',
    answer: "A merchant from Zheng sold pearls in a beautiful box — crafted from expensive fragrant wood, inlaid with jade and kingfisher feathers, fragrant with cinnamon. A buyer from Chu purchased the box, examined the pearl inside, and returned the pearl, keeping only the box. The pearl merchant got his pearl back but lost the sale. From Han Feizi, the idiom means choosing the superficial container over the substantive content — being seduced by presentation to the point of missing what the presentation was meant to hold. Today it is deployed in product design, marketing, and hiring: '买椟还珠式的产品' (a 买椟还珠 product) means beautiful UI, does nothing useful. Also used about hiring someone for an impressive CV who cannot do the actual work.",
  },
  {
    phrase: '势如破竹 (shì rú pò zhú)\nForce Like Splitting Bamboo',
    answer: "The Jin dynasty general Du Yu led a campaign to conquer the Wu kingdom. After rapid victories, some commanders suggested pausing for the winter. Du Yu refused: 'When you split bamboo, once you have split the first few sections, the rest splits instantly along the grain — you cannot stop halfway.' The army continued without pause and Wu surrendered within months. The comparison is specific: bamboo splits dramatically along its natural grain once started, and the force required drops with each section. Today '势如破竹' is used in sports commentary about winning streaks, business reporting about market expansion, and sales discussions about momentum that accelerates rather than tires. '势如破竹地占领市场' means each market entry makes the next one easier. You must find the grain of the bamboo first.",
  },
  {
    phrase: '倚马可待 (yǐ mǎ kě dài)\nCompleted While Leaning Against the Horse',
    answer: "Wang Xiu was a military secretary under the powerful Jin general Huan Wen. Before a campaign, Huan Wen needed a series of official proclamations drafted immediately. He handed Wang Xiu the task. Wang Xiu leaned against a horse, took up his brush, and produced seven separate documents in sequence without pausing, without revisions, without hesitation — each complete and elegant. Huan Wen read through all seven and said nothing needed changing. The idiom means literary or compositional fluency so total that text emerges fully formed without visible effort or revision. Today it is used in hiring for creative roles, in descriptions of journalists under extreme deadline, and as a compliment to writers whose drafts are indistinguishable from finished work. It is also used sardonically about AI writing tools. '他就是那种倚马可待的人' means: the words appear before the need is fully formed. Wang Xiu had no rough draft. He did not need the horse for anything except a surface to lean against.",
  },
  {
    phrase: '一叶知秋 (yī yè zhī qiū)\nOne Leaf Foretells Autumn',
    answer: "From the Huainanzi (2nd century BCE): 'See one leaf fall and you know the year is entering autumn; see one pot of water ice over and you know the winter cold has come across the world.' The fallen leaf is not a fact about autumn — it is a signal from which autumn is deduced with certainty before autumn is visible. Now means perceiving large systemic change from minimal surface evidence. In its best use, it describes genuine perceptual skill rather than lucky guessing. Today it is used in financial analysis, intelligence assessment, and medical diagnosis: the analyst who identified the sector trend from one data point, the physician who reads serious disease from a minor symptom. '一叶知秋的观察力' (the perceptual capacity of 一叶知秋) means the ability to read what is coming before it has arrived. It is also used self-deprecatingly — '我只是一叶知秋，未必准确' means: I saw a leaf fall and drew a conclusion, which may be wrong. The leaf does not fall quietly. It announces something, for those who understand what leaves announce.",
  },
  {
    phrase: '螳臂当车 (táng bì dāng chē)\nMantis Arm Blocking a Chariot',
    answer: "From Zhuangzi. The coachman of King Zhuang of Qi watched a mantis on the road raise both its front legs to stop the approaching chariot. He reported this to the king. The king said: 'If this were a man, he would be called the bravest in the world.' He ordered the chariot to go around the mantis. The anecdote contains two readings that Chinese tradition has preserved simultaneously: the admiring reading — the mantis is brave, commitment over calculation, the gesture is noble regardless of outcome — and the dismissive reading — the mantis is deluded, completely ignorant of the disproportion of forces. Today the idiom is used most often dismissively: small companies suing industry giants, lone protesters facing state power, anyone misreading the scale of the opposition. But before hopeless stands — military, activist, athletic — '螳臂当车' is used admiringly. The chariot went around. This fact is consistently omitted when the idiom is used. It would complicate the lesson.",
  },
  {
    phrase: '百步穿杨 (bǎi bù chuān yáng)\nPiercing the Willow Leaf at a Hundred Paces',
    answer: "The archer Yang Youji of the State of Chu was so precise that when asked to demonstrate his skill, he identified a specific willow leaf at a hundred paces and shot through it. A bystander offered advice: shoot when your spirit is at its highest; if it has fallen by the second arrow, do not fire the third — high spirits produce the truest aim. Yang Youji followed the advice and hit the same leaf with three arrows. The idiom means extraordinary precision in any skilled activity. Today it is used for surgeons whose operations never go wrong, for litigators who choose exactly the right argument, for programmers who write correct code on the first attempt. '百步穿杨的准确性' means not approximate but exactly right. It is also used sardonically about spectacular failures: '连百步穿杨都做不到' (cannot even manage 百步穿杨) means missed from close range. The willow leaf is still on the branch, defining a standard of exactness against which every subsequent performance is measured.",
  },
]
